import CloseIcon from "./close";
import DashboardIcon from "./dashboard";
import DeleteIcon from "./delete";
import EditIcon from "./edit";
import LogoIcon from "./logo";
import MyWordIcon from "./myword";
import PlusIcon from "./plus";
import SearchIcon from "./search";
import SettingsIcon from "./settings";
import LogoutIcon from "./logout";
import EmailIcon from "./email";
export {CloseIcon, DashboardIcon, DeleteIcon, EditIcon, LogoIcon, MyWordIcon, PlusIcon, SearchIcon, SettingsIcon, LogoutIcon, EmailIcon};
